[package]
name = "abc165"
version = "0.1.0"
authors = ["lighttiger2505 <lighttiger2505@gmail.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]
proconio = "*"
[profile.release]
lto = true
panic = 'abort'
